Report
kindnesswall/KindnessWall.KotlinAndroidApp pull request #44
Opened 2022-03-11 11:37 UTC by amirhusseinSSoori

2022-03-11 15:03 UTC, beigirad commented on app/src/main/java/ir/kindnesswall/data/model/CharityReportMessageModel.kt
> +data class CharityReportMessageModel(
we should use @ SerializedName annotations for all network models fields

2022-03-11 15:03 UTC, beigirad commented on app/src/main/java/ir/kindnesswall/data/model/GiftReportMessageModel.kt
> +data class GiftReportMessageModel(
same

2022-03-11 15:03 UTC, beigirad commented on app/src/main/java/ir/kindnesswall/BaseActivity.kt
> +        title: String,
if title and btnLabels are the same, these are redundant.

2022-03-11 15:03 UTC, beigirad commented on app/src/main/java/ir/kindnesswall/data/repository/CharityRepo.kt
> +    fun getMessageCharityReport(viewModelScope: CoroutineScope, charityReportMessageModel: CharityReportMessageModel):
`getMessageCharityReport` is not meaningful for an action that we calling a post api

2022-03-11 15:03 UTC, beigirad commented on app/src/main/java/ir/kindnesswall/utils/widgets/LineEditText.java
> +public class LineEditText extends androidx.appcompat.widget.AppCompatEditText {
I think normal edit text was Ok. It's lines is not necessary for this use-case.

2022-03-11 15:03 UTC, beigirad commented on app/src/main/java/ir/kindnesswall/BaseActivity.kt
> +            layoutInflater.inflate(
You can use `XBinding.inflate` method

2022-03-11 15:03 UTC, beigirad commented on app/src/main/java/ir/kindnesswall/BaseActivity.kt
> +    ): BottomSheetDialog = BottomSheetDialog(this).apply {
There's a `RoundBottomSheetDialogFragment` class for bottom sheets in the project.

2022-03-11 15:03 UTC, beigirad commented on app/src/main/java/ir/kindnesswall/BaseActivity.kt
> +    protected fun showMessageDialog(
Also name of this method is general and isn't related to reporting

2022-03-11 15:03 UTC, beigirad commented on app/src/main/java/ir/kindnesswall/data/remote/network/CharityApi.kt
> +    suspend fun sendReport(@Body model:CharityReportMessageModel):Response<Any>
code is not formatted.
After #42 we shouldn't push reformatted code.

2022-03-11 15:03 UTC, beigirad commented on app/src/main/java/ir/kindnesswall/data/remote/network/GiftApi.kt
> +    suspend fun sendReport(@Body model:GiftReportMessageModel):Response<Any>
same

2022-03-11 15:03 UTC, beigirad commented on app/src/main/java/ir/kindnesswall/di/ViewModelModule.kt
> +    viewModel { CharityViewModel(get(), get(), get(),get()) }
reformat

2022-03-11 15:03 UTC, beigirad commented on app/src/main/java/ir/kindnesswall/view/giftdetail/GiftDetailActivity.kt
> +            getString(R.string.report_message), getString(R.string.report_send), false
same. redundant fields

2022-03-11 15:03 UTC, beigirad commented on app/src/main/java/ir/kindnesswall/view/giftdetail/GiftDetailActivity.kt
> +                    viewModel.giftModel?.userId!!,
sending `userId` instead of `giftId`?

2022-03-11 15:03 UTC, beigirad commented on app/src/main/java/ir/kindnesswall/view/giftdetail/GiftDetailActivity.kt
> +                    viewModel.giftModel?.userId!!,
also avoid using `!!`. 
You can ignore showing dialog when its null

2022-03-11 15:03 UTC, beigirad commented on app/src/main/java/ir/kindnesswall/view/giftdetail/GiftDetailActivity.kt
> +    private fun sendReport() {
We showing a dialog. but method name is `sendReport`.

2022-03-11 15:03 UTC, beigirad commented on app/src/main/java/ir/kindnesswall/view/giftdetail/GiftDetailActivity.kt
> +
unused line spaces

2022-03-11 15:03 UTC, beigirad commented on app/src/main/java/ir/kindnesswall/view/giftdetail/GiftDetailViewModel.kt
> +        return giftRepo.getMessageGiftReport(viewModelScope,giftReportMessageModel)
reformat

2022-03-11 15:03 UTC, beigirad commented on app/src/main/java/ir/kindnesswall/view/main/charity/charitydetail/CharityDetailActivity.kt
> +                    viewModel.charityModel?.userId!!,
It's better to add field names when we pass multiple argument

2022-03-11 15:03 UTC, beigirad commented on app/src/main/java/ir/kindnesswall/view/main/charity/charitydetail/CharityDetailActivity.kt
> +
extra spaces

2022-03-11 15:03 UTC, beigirad commented on app/src/main/res/layout/activity_charity_detail.xml
> +                    android:text="گزارش"
missed hard-coded string

2022-03-11 15:03 UTC, beigirad commented on app/src/main/res/layout/report_bottom_sheet.xml
> +    android:layout_width="match_parent"
formatting issue

2022-03-11 15:03 UTC, beigirad commented on app/src/main/res/values/strings.xml
> +    <string name="cancel_laghve">لفو</string>
`لفو‍` or ‍‍`لغو`

2022-03-11 15:09 UTC, beigirad requested changes
After #42 we should not push any not formatted code in commits. You can [delegate it to AS](https://www.youtube.com/watch?v=KRDJXKt4bTk)

Other things commented.

2022-03-19 10:57 UTC, beigirad commented on app/src/main/java/ir/kindnesswall/data/remote/network/CharityApi.kt
> -    suspend fun sendReport(@Body model:CharityReportMessageModel):Response<Any>
formatting issue

2022-03-20 12:55 UTC, beigirad requested changes

2022-03-20 12:55 UTC, beigirad commented on app/src/main/java/ir/kindnesswall/view/giftdetail/GiftDetailActivity.kt
> +                    charityId = viewModel.giftModel?.userId!!,
You're passing `giftModel?.userId!!` as `charityId`? :|
Also avoid using `!!`

2022-03-20 12:55 UTC, beigirad commented on app/src/main/java/ir/kindnesswall/data/model/ReportMessageModel.kt
> +data class ReportMessageModel(
You should use separate models for separate requests. because they have different structure

2022-03-20 12:55 UTC, beigirad commented on app/src/main/java/ir/kindnesswall/BaseActivity.kt
> +import androidx.appcompat.widget.DialogTitle
remove unused imports

2022-03-20 12:55 UTC, beigirad commented on app/src/main/java/ir/kindnesswall/view/main/charity/add/ReportMessageCharityFragment.kt
> +class ReportMessageCharityFragment(private val charityId: Long) : RoundBottomSheetDialogFragment() {
Fragments must have an empty constructor

2022-03-20 12:55 UTC, beigirad commented on app/src/main/java/ir/kindnesswall/view/main/charity/add/ReportMessageCharityFragment.kt
> +    private lateinit var binding: ReportBottomSheetBinding
this line leaks the view.
You should assign null on onDestroyView

2022-03-20 12:55 UTC, beigirad commented on app/src/main/res/drawable/bg_round_cancel_report.xml
> +    <corners android:radius="15dp"/>
I think these drawables are unused.

2022-03-20 12:59 UTC, beigirad commented on app/src/main/java/ir/kindnesswall/view/main/charity/charitydetail/CharityDetailActivity.kt
> +import timber.log.Timber.Forest.tag
WTF

2022-03-20 13:50 UTC, amirhusseinSSoori commented on app/src/main/res/drawable/bg_round_cancel_report.xml
> +    <corners android:radius="15dp"/>
it's used in report_bottom_sheet.xml

2022-03-20 16:07 UTC, amirhusseinSSoori commented on app/src/main/java/ir/kindnesswall/BaseActivity.kt
> +import androidx.appcompat.widget.DialogTitle
i removed

2022-03-20 17:12 UTC, beigirad commented on app/src/main/java/ir/kindnesswall/view/giftdetail/add/ReportMessageGiftFragment.kt
> +        _binding = null
It's better to write your code before `super.onDestroyView()`

2022-03-20 17:32 UTC, beigirad commented on app/src/main/res/values/strings.xml
> +    <string name="report_send">"ارسال تخلف"</string>
The strings doesn't need double quote.

2022-03-20 17:37 UTC, merged